---
title: "instacart_dashboard"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

Here's a direct link to Aaki's homework 4 repository: https://github.com/ag2965/p8105_hw4_ag2965

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(flexdashboard)
library(plotly)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A - Scatterplot
```{r}
data("instacart")

instacart = 
  instacart %>% 
  as_tibble(instacart)

instacart%>%
  janitor::clean_names()%>%
  sample_n(100)%>%
  group_by(aisle)%>%
   mutate(
     order_dow=as.character(order_dow),
     order_dow=fct_reorder(order_dow,n), #how to reorder the y axis?
     order_dow=recode(order_dow,"0"="Sunday", "1"="Monday", "2"="Tuesday","3"="Wednesday","4"="Thursday","5"="Friday", "6"="Saturday"))%>%
plot_ly(
    x = ~aisle, y = ~order_dow, type = "scatter", mode = "markers",
    color = ~order_hour_of_day, alpha = 0.5)
    

instacart%>%
  count(aisle)%>%
  filter(n>1000)%>%
  mutate(aisle=fct_reorder(aisle,n))%>%
  plot_ly(
    x = ~aisle, y = ~n, type = "scatter", mode = "markers", alpha = 0.5)
```


Column {data-width=350}
-----------------------------------------------------------------------

### Chart B - Boxplot

```{r}
instacart_box = instacart %>% 
  janitor::clean_names()%>%
  filter
  mutate(aisle=fct_reorder(aisle,aisle_id))%>%
  plot_ly(y = ~aisle_id, color = ~aisle, type = "box", colors = "viridis")
  
instacart_box = instacart %>% 
  janitor::clean_names()%>%
  filter(aisle %in% c("baking ingredients","dog food care","packaged vegetables fruits"))%>%
  group_by(aisle)%>%
  count(product_name)%>%
  plot_ly(x=~aisle, y = ~n, color = ~aisle, type = "box", colors = "viridis")
#why doesn't this work?
```

### Chart C - Bar graph

```{r}
instacart %>% 
  janitor::clean_names()%>%
  sample_n(1000)%>%
  count(aisle) %>% 
  mutate(aisle = fct_reorder(aisle, n)) %>% 
  plot_ly(x = ~aisle, y = ~n, color = ~aisle, type = "bar", colors = "viridis")
```

### Chart B

```{r}
nyc_airbnb %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  plot_ly(y = ~price, color = ~neighbourhood, type = "box", colors = "viridis")
```
