---
title: "instacart_dashboard"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

Here's a direct link to Aaki's homework 4 repository: https://github.com/ag2965/p8105_hw4_ag2965

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(flexdashboard)
library(plotly)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A - Scatterplot
```{r}
data("instacart")

instacart = 
  instacart %>% 
  as_tibble(instacart)

instacart%>%
  janitor::clean_names()%>%
  sample_n(1000)%>%
  group_by(aisle)%>%
plot_ly(
    x = ~aisle, y = ~order_hour_of_day, type = "scatter", mode = "markers",
    color = ~order_dow, alpha = 0.5)
```


Column {data-width=350}
-----------------------------------------------------------------------

### Chart B - Boxplot

```{r}
instacart_box = instacart %>% 
  janitor::clean_names()%>%
  sample_n(1000)%>%
  mutate(product_name = fct_reorder(product_name, aisle_id)) %>% 
  plot_ly(y = ~aisle_id, color = ~product_name, type = "box", colors = "viridis")
```

### Chart C - Bar graph

```{r}
instacart %>% 
  janitor::clean_names()%>%
  sample_n(1000)%>%
  count(product_name) %>% 
  mutate(product_name = fct_reorder(product_name, n)) %>% 
  plot_ly(x = ~product_name, y = ~n, color = ~product_name, type = "bar", colors = "viridis")
```

