---
title: "p8105_hw4_ag2965"
author: "Aakriti Shukla"
date: "2022-10-25"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cerulean
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
##Problem 0
This “problem” focuses on structure of your submission, especially the use git and GitHub for reproducibility, R Projects to organize your work, R Markdown to write reproducible reports, relative paths to load data from local files (if necessary), and reasonable naming structures for your files.

To that end:

create a public GitHub repo + local R Project for this assignment 
submit a link to your website (not your repo) via Courseworks
Your solutions to Problems 1 and 2 should be implemented in your .Rmd file(s), and your git commit history should reflect the process you used to solve these Problems.

For Problem 0, we will assess adherence to the instructions above regarding repo structure, git commit history, and whether we are able to knit your .Rmd to ensure that your work is reproducible. Adherence to appropriate styling and clarity of code will be assessed in Problems 1+ using the homework style rubric.

This homework includes figures; the readability of your embedded plots (e.g. font sizes, axis labels, titles) will be assessed in Problems 1+.

##Problem 1
Create a personal website at ag2965.github.io (or some other reasonably-named location). This page can be as extensive as you’d like, but it should include at least:

A brief introductory landing page
A page giving your academic and professional experience (i.e. a resume)
Links in the site navigation for your GitHub account, your email, and other professional networks.
Although it is not required and won’t be graded, I also encourage you to take a few minutes to review your GitHub page – make sure your name and place of work are correct, provide a link to your website, perhaps pin some repositories.

Aakriti Garg Shukla, M.D.
635 W. 165th St, Fifth Floor, Room 533, NY, NY 10032

Here's a direct link to the about page: [about](about.html).

##Problem 2
Create a flexdashboard using plotly for that includes at least three distinct plot types (e.g. scatterplots, line plots, bar plots, box plots, etc.). Use one of the following datasets, and load from the p8105.datasets package:

Instacart
NY NOAA
NYC Restaurant Inspections
These datasets are large; you may want / need to filter or randomly sample from the complete dataset to ensure a reasonable product.

